# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'demo_app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  use_frameworks!
  pod 'TensorFlowLiteTaskVision'

  # Pods for demo_app

  target 'demo_appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'demo_appUITests' do
    # Pods for testing
  end

end
